# Generated by Django 6.0.3 on 2026-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_jobapplication_feed_back_jobapplication_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
