# Generated by Django 6.0.3 on 2026-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('office_location', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('source_of_application', models.CharField(max_length=50)),
                ('feed_back', models.TextField(max_length=500)),
            ],
        ),
    ]
