# Generated by Django 6.0.4 on 2026-05-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
