# Generated by Django 6.0.3 on 2026-04-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
